return {
  {
    "folke/snacks.nvim",
    opts = {
      picker = {
        win = {
          input = {
            keys = {
              ["<C-w>"] = false,
              ["<A-c>"] = false,
              ["<A-d>"] = false,
              ["<A-f>"] = false,
              ["<A-h>"] = false,
              ["<A-i>"] = false,
              ["<A-m>"] = false,
              ["<A-p>"] = false,
              ["<A-r>"] = false,
              ["<A-s>"] = false,
              ["<A-t>"] = false,
              ["<A-w>"] = false,
              ["<C-w>c"] = { "toggle_cwd", mode = { "i", "n" } },
              ["<C-w>d"] = { "inspect", mode = { "i", "n" } },
              ["<C-w>f"] = { "toggle_follow", mode = { "i", "n" } },
              ["<C-w>h"] = { "toggle_hidden", mode = { "i", "n" } },
              ["<C-w>i"] = { "toggle_ignored", mode = { "i", "n" } },
              ["<C-w>m"] = { "toggle_maximize", mode = { "i", "n" } },
              ["<C-w>p"] = { "toggle_preview", mode = { "i", "n" } },
              ["<C-w>r"] = { "toggle_regex", mode = { "i", "n" } },
              ["<C-w>s"] = { "flash", mode = { "i", "n" } },
              ["<C-w>t"] = { "trouble_open", mode = { "i", "n" } },
              ["<C-w>w"] = { "cycle_win", mode = { "i", "n" } },
            },
          },
          list = {
            keys = {
              ["<A-d>"] = false,
              ["<A-f>"] = false,
              ["<A-h>"] = false,
              ["<A-i>"] = false,
              ["<A-m>"] = false,
              ["<A-p>"] = false,
              ["<A-w>"] = false,
              ["<C-w>d"] = { "inspect", mode = { "n", "x" } },
              ["<C-w>f"] = { "toggle_follow", mode = { "n", "x" } },
              ["<C-w>h"] = { "toggle_hidden", mode = { "n", "x" } },
              ["<C-w>i"] = { "toggle_ignored", mode = { "n", "x" } },
              ["<C-w>m"] = { "toggle_maximize", mode = { "n", "x" } },
              ["<C-w>p"] = { "toggle_preview", mode = { "n", "x" } },
              ["<C-w>r"] = { "toggle_regex", mode = { "n", "x" } },
              ["<C-w>w"] = { "cycle_win", mode = { "n", "x" } },
            },
          },
          preview = {
            keys = {
              ["<A-w>"] = false,
              ["<C-w>d"] = "inspect",
              ["<C-w>f"] = "toggle_follow",
              ["<C-w>h"] = "toggle_hidden",
              ["<C-w>i"] = "toggle_ignored",
              ["<C-w>m"] = "toggle_maximize",
              ["<C-w>p"] = "toggle_preview",
              ["<C-w>r"] = "toggle_regex",
              ["<C-w>w"] = "cycle_win",
            },
          },
        },
      },
    },
  },
}
