return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    opts.ensure_installed = {
      "arduino",
      "bash",
      "c",
      "diff",
      "dockerfile",
      -- Git
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      -- Go
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "gowork",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "latex",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "nginx",
      "nix",
      "printf",
      "python",
      "query",
      "racket",
      "regex",
      "rust",
      "sql",
      "ssh_config",
      "swift",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    }
  end,
}
