eval "$(/usr/local/Homebrew/bin/brew shellenv)"


# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

# Added by swiftly
. "/Users/devspaceship/.swiftly/env.sh"

export LANG=en_US.UTF-8
export TERM="xterm-256color"
export COLORTERM="truecolor"
export EDITOR="nvim"
export MANPATH="/usr/local/man:$MANPATH"
export XDG_CONFIG_HOME="$HOME/.config"
export ZSH="$HOME/.oh-my-zsh"
export GPG_TTY=$(tty)

export PNPM_HOME="/Users/devspaceship/Library/pnpm"
export NVM_DIR="$HOME/.nvm"

export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="$PNPM_HOME:$PATH"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/bin/flutter/bin"
export PATH="$PATH:$HOME/Node/bin"
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Created by `pipx` on 2024-01-11 22:09:36
export PATH="$PATH:/Users/devspaceship/.local/bin"

# MacPorts Installer addition on 2024-04-12_at_16:51:19: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2024-04-12_at_16:51:19: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH="/opt/local/share/man:$MANPATH"
# Finished adapting your MANPATH environment variable for use with MacPorts.

# Setting PATH for Python 3.10
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH 
