# vim: ft=zsh
. ~/.zsh_helpers

if_debug path_print '$PATH before zprofile'


# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
export JAVA_HOME="$(/usr/libexec/java_home)"

export LANG=en_US.UTF-8
export EDITOR="nvim"
export MANPATH="/usr/local/man:$MANPATH"
export XDG_CONFIG_HOME="$HOME/.config"
export ZSH="$HOME/.oh-my-zsh"
export GPG_TTY=$(tty)
export PNPM_HOME="$HOME/Library/pnpm"
export NVM_DIR="$HOME/.nvm"
# export CC=/usr/bin/clang
# export CXX=/usr/bin/clang++

export OPENCODE_EXPERIMENTAL_LSP_TOOL=true
export OPENCODE_ENABLE_EXA=true


if [ -f "$HOME/.config/home-manager/.env" ]; then
    set -a
    source "$HOME/.config/home-manager/.env"
    set +a
fi

path_prepend "$PNPM_HOME"
path_prepend "/usr/bin"
path_append "$HOME/.cargo/bin"
path_append "$HOME/.local/bin"
path_append "$HOME/.local/share/nvim/mason/bin"
path_append "$HOME/go/bin"
path_append "$HOME/bin/flutter/bin"
path_append "$HOME/Node/bin"
path_append "$HOME/Library/Android/sdk/platform-tools"
path_append "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Homebrew
if [ -x "$(command -v brew)" ]; then
    eval "$(brew shellenv)"
    path_prepend "/opt/homebrew/opt/openjdk/bin"

    # Apple Silicon Rust fix
    export LIBRARY_PATH=$LIBRARY_PATH:$(brew --prefix)/lib:$(brew --prefix)/opt/libiconv/lib
fi
# End Homebrew

export PATH

if_debug path_print '$PATH after zprofile'

if [ -f "$HOME/.env" ]; then
    set -a
    source "$HOME/.env"
    set +a
fi
