# Oh My Zsh Config
export PATH="$HOME/bin:/usr/local/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"

zstyle ':omz:update' auto
zstyle ':omz:update' frequency 10

COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd/mm/yyyy"

plugins=(
    colored-man-pages
    command-not-found
    copyfile
    docker
    docker-compose
    gh
    git
    gitfast
    rust
    sudo
    timer
)

source $ZSH/oh-my-zsh.sh

# Plugins Config
TIMER_FORMAT='[%d]'

# Zsh Config
bindkey -v

# Aliases
## Docker Compose
alias dc='docker compose'
alias dcu='docker compose up'
alias dcud='docker compose up -d'
alias dcd='docker compose down'
alias dcdv='docker compose down -v'
alias dcl='docker compose logs'
alias dclf='docker compose logs -f'
alias dce='docker compose exec'
alias dcr='docker compose run'

## Home Manager
alias hm='home-manager'
alias hms='home-manager switch'

## Nvim
alias vim='nvim'
alias vi='nvim'
alias v='nvim'

## Pnpm
alias pn='pnpm'
alias pnx='pnpx'
alias npm='pnpm'
alias npx='pnpx'

## Git
alias lg='lazygit'

# User Config
export EDITOR="nvim"
export LANG=en_US.UTF-8
export TERM="xterm-256color"

# Starship Prompt
eval "$(starship init zsh)"

# Path Config
export PATH="$PATH:$HOME/bin/flutter/bin"
export PATH="$PATH:$HOME/Node/bin"
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"
export MANPATH="/usr/local/man:$MANPATH"

fpath+="$HOME/.zsh/completions"

# Created by `pipx` on 2024-01-11 22:09:36
export PATH="$PATH:/Users/devspaceship/.local/bin"
export PATH="$PATH:/usr/local/opt/ruby/bin"

# Ruby
eval "$(rbenv init - zsh)"
## fix pre-commit being shadowed by rbenv
alias pre-commit=/usr/local/bin/pre-commit

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

# pnpm
export PNPM_HOME="/Users/devspaceship/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
