. ~/.zsh_helpers

zstyle ':omz:update' auto
zstyle ':omz:update' frequency 10

COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd/mm/yyyy"

plugins=(
    aws
    colored-man-pages
    command-not-found
    copyfile
    docker
    docker-compose
    gh
    git
    gitfast
    golang
    rust
    ssh
    sudo
    terraform
    timer
)

source $ZSH/oh-my-zsh.sh
fpath+="$HOME/.zsh/completions"

# Plugins Config
TIMER_FORMAT='[%d]'

# Zsh Config
bindkey -v

# Aliases
## Docker Compose
alias dc='docker compose'
alias dcu='docker compose up'
alias dcud='docker compose up -d'
alias dcd='docker compose down'
alias dcdv='docker compose down -v'
alias dcl='docker compose logs'
alias dclf='docker compose logs -f'
alias dce='docker compose exec'
alias dcr='docker compose run'

## Home Manager
alias hm='home-manager'
alias hms='home-manager switch --flake .#devspaceship'

## Nvim
alias v='nvim'
alias vi='nvim'
alias vim='nvim'

## Pnpm
alias pn='pnpm'
alias pnx='pnpx'
alias npm='pnpm'
alias npx='pnpx'

## Git
alias lg='lazygit'

## Terraform
alias tf='terraform'
alias tfi='terraform init'
alias tfp='terraform plan'
alias tfa='terraform apply'

## Tmux
alias t='tmux'
alias ta='tmux attach'

# Starship Prompt
eval "$(starship init zsh)"

# NVM
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

path_prepend "$HOME/bin"
path_prepend "$HOME/.swiftly/bin"
export PATH

if_debug path_print '$PATH after zshrc'
